import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MammTv",
  description: "Generated by create next app",
  icons: {
    icon: "./images/mamm-favicon2.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
